services:
  mongdb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rou
      - MONGO_INITDB_ROOT_PASSWORD=rou
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rou
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rou
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
